name: Android CI/CD
on:
  push:
    branches: [master] # Chạy khi push lên nhánh main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout mã nguồn
    - uses: actions/checkout@v3

    # Cài đặt Flutter
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3' # Chọn phiên bản Flutter phù hợp
        channel: 'stable'

    # Cài đặt dependencies
    - run: flutter pub get

    # Cài đặt Fastlane
    - run: sudo gem install fastlane

    # Chạy Fastlane để build APK
    - run: cd android && fastlane android build

    # (Tùy chọn) Lưu APK làm artifact để tải về kiểm tra
    - uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk